<a href="https://colab.research.google.com/github/AnnMariyJoy/MCALAB/blob/main/Miniproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv("/content/heart_attack_prediction_dataset.csv")
df

Patient ID  Age     Sex  Cholesterol Blood Pressure  Heart Rate  \
0       BMW7812   67    Male          208         158/88          72   
1       CZE1114   21    Male          389         165/93          98   
2       BNI9906   21  Female          324         174/99          72   
3       JLN3497   84    Male          383        163/100          73   
4       GFO8847   66    Male          318          91/88          93   
...         ...  ...     ...          ...            ...         ...   
8758    MSV9918   60    Male          121          94/76          61   
8759    QSV6764   28  Female          120        157/102          73   
8760    XKA5925   47    Male          250         161/75         105   
8761    EPE6801   36    Male          178         119/67          60   
8762    ZWN9666   25  Female          356         138/67          75   

      Diabetes  Family History  Smoking  Obesity  ...  \
0            0               0        1        0  ...   
1            1               1        1        1  ...   
2            1               0        0        0  ...   
3            1               1        1        0  ...   
4            1               1        1        1  ...   
...        ...             ...      ...      ...  ...   
8758         1               1        1        0  ...   
8759         1               0        0        1  ...   
8760         0               1        1        1  ...   
8761         1               0        1        0  ...   
8762         1               1        0        0  ...   

      Sedentary Hours Per Day  Income        BMI  Triglycerides  \
0                    6.615001  261404  31.251233            286   
1                    4.963459  285768  27.194973            235   
2                    9.463426  235282  28.176571            587   
3                    7.648981  125640  36.464704            378   
4                    1.514821  160555  21.809144            231   
...                       ...     ...        ...            ...   
8758                10.806373  235420  19.655895             67   
8759                 3.833038  217881  23.993866            617   
8760                 2.375214   36998  35.406146            527   
8761                 0.029104  209943  27.294020            114   
8762                 9.005234  247338  32.914151            180   

      Physical Activity Days Per Week  Sleep Hours Per Day         Country  \
0                                   0                    6       Argentina   
1                                   1                    7          Canada   
2                                   4                    4          France   
3                                   3                    4          Canada   
4                                   1                    5        Thailand   
...                               ...                  ...             ...   
8758                                7                    7        Thailand   
8759                                4                    9          Canada   
8760                                4                    4          Brazil   
8761                                2                    8          Brazil   
8762                                7                    4  United Kingdom   

          Continent           Hemisphere  Heart Attack Risk  
0     South America  Southern Hemisphere                  0  
1     North America  Northern Hemisphere                  0  
2            Europe  Northern Hemisphere                  0  
3     North America  Northern Hemisphere                  0  
4              Asia  Northern Hemisphere                  0  
...             ...                  ...                ...  
8758           Asia  Northern Hemisphere                  0  
8759  North America  Northern Hemisphere                  0  
8760  South America  Southern Hemisphere                  1  
8761  South America  Southern Hemisphere                  0  
8762         Europe  Northern H

In [39]:
df.isnull().sum()

Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [40]:
df['Sex'] = df['Sex'].map({'Male': 1, 'Female': 0})  # Simple binary encoding

In [41]:
# Split the 'Blood Pressure' column into 'Systolic' and 'Diastolic'
df[['Systolic', 'Diastolic']] = df['Blood Pressure'].str.split('/', n=1, expand=True)


# Convert the new columns to numeric values
df['Systolic'] = pd.to_numeric(df['Systolic'])
df['Diastolic'] = pd.to_numeric(df['Diastolic'])

In [42]:
df = df.drop('Blood Pressure', axis=1)

In [81]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['Age', 'Cholesterol', 'Systolic', 'Diastolic','Cholesterol','Heart Rate','Diabetes','Family History']] = scaler.fit_transform(df[['Age', 'Cholesterol', 'Systolic', 'Diastolic','Cholesterol','Heart Rate','Diabetes','Family History']])

In [82]:
df

Patient ID       Age  Sex  Cholesterol  Heart Rate  Diabetes  \
0       BMW7812  0.625557    1    -0.641579   -0.147042 -1.369651   
1       CZE1114 -1.539322    1     1.596895    1.118179  0.730113   
2       BNI9906 -1.539322    0     0.793023   -0.147042  0.730113   
3       JLN3497  1.425621    1     1.522691   -0.098380  0.730113   
4       GFO8847  0.578495    1     0.718820    0.874867  0.730113   
...         ...       ...  ...          ...         ...       ...   
8758    MSV9918  0.296119    1    -1.717530   -0.682328  0.730113   
8759    QSV6764 -1.209884    0    -1.729898   -0.098380  0.730113   
8760    XKA5925 -0.315695    1    -0.122154    1.458815 -1.369651   
8761    EPE6801 -0.833383    1    -1.012597   -0.730990  0.730113   
8762    ZWN9666 -1.351072    0     1.188775   -0.001055  0.730113   

      Family History  Smoking  Obesity  Alcohol Consumption  ...        BMI  \
0          -0.986061        1        0                    0  ...  31.251233   
1           1.014136        1        1                    1  ...  27.194973   
2          -0.986061        0        0                    0  ...  28.176571   
3           1.014136        1        0                    1  ...  36.464704   
4           1.014136        1        1                    0  ...  21.809144   
...              ...      ...      ...                  ...  ...        ...   
8758        1.014136        1        0                    1  ...  19.655895   
8759       -0.986061        0        1                    0  ...  23.993866   
8760        1.014136        1        1                    1  ...  35.406146   
8761       -0.986061        1        0                    0  ...  27.294020   
8762        1.014136        0        0                    1  ...  32.914151   

     Triglycerides  Physical Activity Days Per Week  Sleep Hours Per Day  \
0              286                                0                    6   
1              235                                1                    7   
2              587                                4                    4   
3              378                                3                    4   
4              231                                1                    5   
...            ...                              ...                  ...   
8758            67                                7                    7   
8759           617                                4                    9   
8760           527                                4                    4   
8761           114                                2                    8   
8762           180                                7                    4   

             Country      Continent           Hemisphere  Heart Attack Risk  \
0          Argentina  South America  Southern Hemisphere                  0   
1             Canada  North America  Northern Hemisphere                  0   
2             France         Europe  Northern Hemisphere                  0   
3             Canada  North America  Northern Hemisphere                  0   
4           Thailand           Asia  Northern Hemisphere                  0   
...              ...            ...                  ...                ...   
8758        Thailand           Asia  Northern Hemisphere                  0   
8759          Canada  North America  Northern Hemisphere                  0   
8760          Brazil  South America  Southern Hemisphere                  1   
8761          Brazil  South America  Southern Hemisphere                  0   
8762  United Kingdom         Europe  Northern Hemisphere                  1   

      Systolic  Diastolic  
0     0.870044   0.193782  
1     1.135714   0.534480  
2     1.477290   0.943319  
3     1.059809   1.011458  
4    -1.672797   0.193782  
...        ...        ...  
8758 -1.558939  -0.623895  
8759  0.832092   1.147738  
8760  0.983903  -0.692035  
8761 -0.610117  -1.237152  
8762  0.110987  -1.237152  

[8763 rows x 27 columns]

In [83]:
x = df[['Age', 'Cholesterol', 'Sex', 'Systolic','Diastolic','Cholesterol','Heart Rate','Diabetes','Family History']] # If the correct column name is 'BloodPressure'
x



Age  Cholesterol  Sex  Systolic  Diastolic  Cholesterol  \
0     0.625557    -0.641579    1  0.870044   0.193782    -0.641579   
1    -1.539322     1.596895    1  1.135714   0.534480     1.596895   
2    -1.539322     0.793023    0  1.477290   0.943319     0.793023   
3     1.425621     1.522691    1  1.059809   1.011458     1.522691   
4     0.578495     0.718820    1 -1.672797   0.193782     0.718820   
...        ...          ...  ...       ...        ...          ...   
8758  0.296119    -1.717530    1 -1.558939  -0.623895    -1.717530   
8759 -1.209884    -1.729898    0  0.832092   1.147738    -1.729898   
8760 -0.315695    -0.122154    1  0.983903  -0.692035    -0.122154   
8761 -0.833383    -1.012597    1 -0.610117  -1.237152    -1.012597   
8762 -1.351072     1.188775    0  0.110987  -1.237152     1.188775   

      Heart Rate  Diabetes  Family History  
0      -0.147042 -1.369651       -0.986061  
1       1.118179  0.730113        1.014136  
2      -0.147042  0.730113       -0.986061  
3      -0.098380  0.730113        1.014136  
4       0.874867  0.730113        1.014136  
...          ...       ...             ...  
8758   -0.682328  0.730113        1.014136  
8759   -0.098380  0.730113       -0.986061  
8760    1.458815 -1.369651        1.014136  
8761   -0.730990  0.730113       -0.986061  
8762   -0.001055  0.730113        1.014136  

[8763 rows x 9 columns]

In [84]:
y=df['Heart Attack Risk']
y

0       0
1       0
2       0
3       0
4       0
       ..
8758    0
8759    0
8760    1
8761    0
8762    1
Name: Heart Attack Risk, Length: 8763, dtype: int64

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [86]:
# Train-test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)



In [87]:
# Standardize the features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [88]:
pca = PCA(n_components=0.95)  # Keep 95% of variance
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

In [89]:
# Hyperparameter tuning: Find the best `k`
best_accuracy = 0
best_k = 1
for k in range(1, 200):
    knn_model = KNeighborsClassifier(n_neighbors=k)
    knn_model.fit(x_train, y_train)
    y_pred = knn_model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f'k={k}: Accuracy={accuracy:.2f}')
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print(f'Best k: {best_k} with Accuracy: {best_accuracy:.2f}')

k=1: Accuracy=0.53
k=2: Accuracy=0.61
k=3: Accuracy=0.55
k=4: Accuracy=0.60
k=5: Accuracy=0.56
k=6: Accuracy=0.59
k=7: Accuracy=0.56
k=8: Accuracy=0.59
k=9: Accuracy=0.58
k=10: Accuracy=0.60
k=11: Accuracy=0.59
k=12: Accuracy=0.60
k=13: Accuracy=0.59
k=14: Accuracy=0.61
k=15: Accuracy=0.59
k=16: Accuracy=0.61
k=17: Accuracy=0.60
k=18: Accuracy=0.62
k=19: Accuracy=0.61
k=20: Accuracy=0.62
k=21: Accuracy=0.61
k=22: Accuracy=0.63
k=23: Accuracy=0.61
k=24: Accuracy=0.62
k=25: Accuracy=0.62
k=26: Accuracy=0.62
k=27: Accuracy=0.62
k=28: Accuracy=0.62
k=29: Accuracy=0.62
k=30: Accuracy=0.62
k=31: Accuracy=0.62
k=32: Accuracy=0.62
k=33: Accuracy=0.62
k=34: Accuracy=0.63
k=35: Accuracy=0.62
k=36: Accuracy=0.63
k=37: Accuracy=0.62
k=38: Accuracy=0.63
k=39: Accuracy=0.63
k=40: Accuracy=0.63
k=41: Accuracy=0.63
k=42: Accuracy=0.63
k=43: Accuracy=0.63
k=44: Accuracy=0.63
k=45: Accuracy=0.63
k=46: Accuracy=0.63
k=47: Accuracy=0.63
k=48: Accuracy=0.64
k=49: Accuracy=0.64
k=50: Accuracy=0.64
k=51: Acc

In [73]:
# Train the model
knn_model = KNeighborsClassifier(n_neighbors=10)
knn_model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [74]:
# Make predictions
y_pred = knn_model.predict(x_test)

In [75]:
x_test

array([[-1.41422496, -1.70975751, -0.02826269, ...,  0.96256796,
        -0.31952102,  0.27475315],
       [-1.76188043,  0.07534307, -1.1049432 , ..., -1.92896966,
         0.88533812,  0.23421334],
       [-1.40411252, -0.50670052,  0.1012363 , ..., -1.28578277,
         0.41690448,  0.27197008],
       ...,
       [ 1.42510354, -2.08181475, -0.72744243, ...,  0.44535259,
         0.3529175 , -0.24407594],
       [ 1.11268479,  0.75873941,  0.08131646, ..., -1.98138438,
        -0.68852954, -0.15162013],
       [-1.36177226,  1.31684976, -0.57305782, ..., -1.23006471,
        -0.92132594, -0.01983848]])

In [76]:
# Evaluate the model
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print('Classification Report:')
print(classification_report(y_test, y_pred))

Accuracy: 0.6160867084997148
Confusion Matrix:
[[1012  113]
 [ 560   68]]
Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.90      0.75      1125
           1       0.38      0.11      0.17       628

    accuracy                           0.62      1753
   macro avg       0.51      0.50      0.46      1753
weighted avg       0.55      0.62      0.54      1753



In [80]:
import numpy as np
new_input = np.array([[55, 220, 1, 130, 85,0,1,0]])

In [ ]:
scaler = StandardScaler()
new_input = scaler.fit_transform(new_input)

In [79]:
new_input = pca.transform(new_input)

In [60]:
new_input

array([[-4.77618542e-17,  6.96009685e-18, -9.47680595e-18,
         1.28152338e-17,  5.16394483e-18,  3.06919371e-17]])

In [61]:
prediction = knn_model.predict(new_input)

In [62]:
prediction

array([0])